# Generated by Django 6.0.2 on 2026-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='profile_photos/'),
        ),
    ]
